/**
 * Child.ts
 * All TypeScript types related to the child user, their profile,
 * memory layers, and accessibility preferences.
 *
 * Imported by: supabase/profiles.ts, supabase/memory.ts,
 *              azure/search.ts, rag/retrieveChildProfile.ts,
 *              and all API routes that touch child data.
 */

// ── Subjects ─────────────────────────────────────────────────────────────────

/** The three domain-locked subjects available in Talewind. */
export type Subject = "animals" | "space" | "math";

// ── Reading & Tone ────────────────────────────────────────────────────────────

/** How the child prefers to experience stories. */
export type ReadingMode = "read_to_me" | "read_together";

/** The narrative tone the child chose during intake. */
export type StoryTone = "calm" | "exciting" | "silly";

// ── Accessibility ─────────────────────────────────────────────────────────────

/** All accessibility settings persisted per child profile. Set by parent. */
export interface AccessibilityPreferences {
  reducedMotion: boolean;
  dyslexiaFont: boolean;
  highContrast: boolean;
  largerText: boolean;
  captionsEnabled: boolean;
  captionFontSize: number; // in px, default 18
  narrationSpeed: "slower" | "normal" | "faster";
}

// ── Child Profile (Stable) ────────────────────────────────────────────────────

/**
 * The stable profile written during Magic Door intake and updated
 * by the parent. Lives in the `children` Supabase table and is
 * indexed as the base fields of the child's Azure AI Search doc.
 */
export interface ChildProfile {
  id: string;
  parentId: string;
  name: string;
  age: number;
  grade: number;
  /** Free-form list of interests entered by parent. */
  interests: string[];
  /** Self-reported reading comfort level. Set by parent. */
  readingComfort: "beginner" | "developing" | "confident";
  preferredSubject: Subject | null;
  readingMode: ReadingMode | null;
  storyTone: StoryTone | null;
  /** Favorite color collected in intake Screen 1. */
  favoriteColor: string | null;
  /** Favorite animal collected in intake Screen 1. */
  favoriteAnimal: string | null;
  /**
   * Index (0-based) of the last rotating question asked in Screen 1.
   * Used to determine which question to ask in the next session.
   * -1 means no question beyond the first two has been asked yet.
   */
  lastQuestionAsked: number;
  /** Most recently collected personal detail from the rotating RAG bank. */
  latestPersonalDetail: string | null;
  accessibility: AccessibilityPreferences;
  createdAt: string; // ISO 8601
}

// ── Session Memory ────────────────────────────────────────────────────────────

/**
 * Memory captured for a single completed session.
 * Appended to child_memory.session_history after every session.
 */
export interface SessionMemoryEntry {
  sessionId: string;
  subject: Subject;
  storyTitle: string;
  quizScore: number; // 0–100
  adaptationResult: "simplify" | "enrich" | "hold";
  /** Scenes the child asked to make easier (voice command). */
  madeEasierScenes: string[];
  /** Topics the child struggled with in this session. */
  struggledWith: string[];
  /** Themes or topics that worked well for the child. */
  workedWell: string[];
  /** Curriculum topics covered in this session. */
  topicsCovered: string[];
  /** Tone used in this session. */
  tone: StoryTone;
  createdAt: string; // ISO 8601
}

// ── Derived Memory ────────────────────────────────────────────────────────────

/**
 * Inferences about the child generated by GPT-4o mini after 3+ sessions.
 * Natural-language strings, 2–4 entries max.
 *
 * Example: "Responds well to animal stories", "Struggles with math vocabulary"
 */
export type DerivedMemory = string[];

// ── Child Memory (all three layers) ──────────────────────────────────────────

/**
 * The full memory record for a child. Lives in the `child_memory` table.
 * Also serialised into the Azure AI Search `talewind-children` index doc.
 */
export interface ChildMemory {
  id: string;
  childId: string;
  /** Snapshot of the stable ChildProfile fields relevant for story generation. */
  stableProfile: Pick<
    ChildProfile,
    | "name"
    | "age"
    | "grade"
    | "interests"
    | "readingComfort"
    | "favoriteColor"
    | "favoriteAnimal"
    | "latestPersonalDetail"
    | "preferredSubject"
    | "readingMode"
    | "storyTone"
  >;
  /** Array of past session memory entries, newest last. */
  sessionHistory: SessionMemoryEntry[];
  /** GPT-4o mini inferences generated after ≥3 sessions. */
  derivedMemory: DerivedMemory;
  /** Current difficulty adaptation directive. */
  currentAdaptation: "simplify" | "enrich" | "hold";
  updatedAt: string; // ISO 8601
}

// ── Azure AI Search child profile doc ────────────────────────────────────────

/**
 * The shape of a document stored in the `talewind-children` Azure AI Search
 * index. This is a flattened version of ChildMemory for efficient retrieval.
 */
export interface ChildSearchDoc {
  /** Primary key — must be the child's UUID. */
  id: string;
  name: string;
  subject: string;
  readingMode: string;
  storyTone: string;
  favoriteColor: string;
  favoriteAnimal: string;
  personalDetails: string;
  currentDifficulty: string;
  sessionCount: number;
  lastQuestionAsked: number;
  updatedAt: string; // ISO 8601
}
