/**
 * Quiz.ts
 * TypeScript types for quiz questions, answers, scoring, and safety results.
 *
 * Imported by: /src/app/api/quiz/route.ts,
 *              /src/lib/safety/checkQuizOutput.ts,
 *              /src/lib/supabase/sessions.ts
 */

// ── Question ──────────────────────────────────────────────────────────────────

/**
 * A single quiz question generated by the Quiz Agent from story content.
 * Questions are designed for first-grade level (ages 5–7) and must be
 * answerable by voice or typed text.
 */
export interface QuizQuestion {
  /** Unique identifier for this question within the quiz. */
  id: string;
  /** The question text shown to and spoken aloud for the child. */
  question: string;
  /**
   * The expected answer or keywords the scoring function looks for.
   * This is server-side only — never sent to the client.
   */
  expectedAnswer: string;
  /** Zero-based position in the quiz (0 = first question). */
  index: number;
}

// ── Raw Quiz Agent Output ─────────────────────────────────────────────────────

/**
 * The raw JSON structure returned by GPT-4o mini before safety checking.
 * The Quiz Agent is prompted to return exactly this shape.
 */
export interface RawQuizAgentOutput {
  questions: Array<{
    id: string;
    question: string;
    expectedAnswer: string;
    index: number;
  }>;
}

// ── Answer ────────────────────────────────────────────────────────────────────

/**
 * A child's answer to a single quiz question.
 * Input is accepted via voice (STT) or typed text.
 */
export interface QuizAnswer {
  questionId: string;
  /** The raw text of the child's answer. Sanitised before use. */
  answerText: string;
  /** Input modality used by the child. */
  inputMode: "voice" | "typed";
}

// ── Score ─────────────────────────────────────────────────────────────────────

/**
 * Scoring result for a single question.
 */
export interface QuestionScore {
  questionId: string;
  /** Whether the answer was marked correct. */
  correct: boolean;
  /**
   * 0–100 score for this question. 100 = fully correct,
   * partial credit can be given for near-correct answers.
   */
  score: number;
}

/**
 * Aggregated quiz score for the full session.
 * Stored in the `sessions` table and used to determine adaptation.
 */
export interface QuizScore {
  /** Overall score 0–100 (average of all question scores). */
  totalScore: number;
  /** Breakdown per question. */
  questionScores: QuestionScore[];
  /**
   * Adaptation directive derived from the score.
   * Below threshold → "simplify"; above threshold → "enrich"; at threshold → "hold".
   */
  adaptationResult: "simplify" | "enrich" | "hold";
}

// ── Quiz Safety Result ────────────────────────────────────────────────────────

/**
 * Return value from checkQuizOutput.ts.
 * If passed is false, rewritten contains the safe replacement questions.
 */
export interface QuizSafetyResult {
  passed: boolean;
  /** The validated (or rewritten) questions. Undefined only if catastrophic failure. */
  questions: QuizQuestion[] | undefined;
  /** True if questions required rewriting before being returned. */
  wasRewritten: boolean;
}
